version: 0.2

phases:
  install:
    commands:
      - echo "command are executed here"
  build:
    commands:
      - echo "Listing files to check for index.html"
      - ls -la
      - echo "Copying index.html to /usr/share/nginx/html"
      - cp index.html /var/www/html/

artifacts:
  files:
    - '**/*'
